version: '3.4'
services:
  nginx:
    image: rainist/nginx:1.15.9
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  app:
    build:
      context: .
      target: base
    command: sh -c "npm run dev"
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - .:/app
